main: me.jedimastersoda.transfer.TransferPacket
name: ${project.name}
author: JediMasterSoda
version: ${project.version}-${git.commit.id.abbrev}
api-version: 1.14
website: "https://github.com/JediMasterSoda/Transfer-Packet"